# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author1_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Author2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author2_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=450)),
                ('Opening_Para', models.CharField(max_length=4000)),
                ('Post_text', models.TextField()),
                ('Author1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Author1')),
                ('Author2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Author2')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Tags',
            field=models.ManyToManyField(to='blog_app.Tags'),
        ),
    ]
