# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
    ]


