# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
