# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20171011_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=450)),
                ('Opening_Para', models.CharField(max_length=4000)),
                ('Post_text', models.TextField()),
                ('Image', models.ImageField(max_length=255, null=True, upload_to='')),
                ('createdDate', models.DateTimeField()),
                ('Title_Opening_Combined', models.TextField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(verbose_name=2)),
            ],
            options={
                'db_table': 'post_view',
                'ordering': ['-createdDate'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-createdDate']},
        ),
        migrations.AddField(
            model_name='post',
            name='dayNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='month',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
