# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20171018_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='monthNumber',
            field=models.IntegerField(null=True),
        ),
    ]
