# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 09:15
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_post_monthnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentTest',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='BlogContent'),
        ),
    ]
