# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 09:28
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_post_contenttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentTextUploader',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
