# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 15:47
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_post_contenttextuploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Post_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
