# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_auto_20171021_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contentTest',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contentTextUploader',
        ),
    ]
