# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_auto_20171021_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dayNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='monthNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
